[package]
name = "findpanics"
version = "0.1.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Find calls to panic functions in rust executables"
repository = "https://github.com/philipc/findpanics"
readme = "README.md"
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"

[dependencies]
addr2line = "0.6"
clap = "2"
failure = "0.1"
gimli = "0.15"
home = "0.3"
memmap = "0.6"
object = "0.7"
panopticon-core = { git = "https://github.com/das-labor/panopticon" }
panopticon-amd64 = { git = "https://github.com/das-labor/panopticon" }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
